[platformio]
default_envs = teensy40_config_serial

[env]
platform = teensy
board = teensy40
framework = arduino
board_build.f_cpu = 600000000L

[env:teensy40_xinput]
board_build.usb = xinput
extra_scripts =
  pre:tools/apply_teensy_xinput_core.py
build_flags =
  -DFIGHTING_TEENSY_XINPUT_MODE=1
  -UUSB_SERIAL
  -DUSB_XINPUT
lib_deps =
  https://github.com/dmadison/ArduinoXInput.git

[env:teensy40_config_serial]
board_build.usb = serial
extra_scripts =
  pre:tools/apply_teensy_xinput_core.py
build_flags =
  -DFIGHTING_TEENSY_CONFIG_MODE=1
